//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Dropper"",
            ""id"": ""3d2052d5-a651-46e0-b1f1-75147dcbcc0a"",
            ""actions"": [
                {
                    ""name"": ""DropButton"",
                    ""type"": ""Button"",
                    ""id"": ""e9798791-2b45-4cb4-a7e6-c48b80b81b96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0502ab84-b7c7-4b1a-933d-b7a5f76be6e9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41c7a7e9-5460-4839-91a1-1696ac3e02bc"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DropButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dropper
        m_Dropper = asset.FindActionMap("Dropper", throwIfNotFound: true);
        m_Dropper_DropButton = m_Dropper.FindAction("DropButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dropper
    private readonly InputActionMap m_Dropper;
    private IDropperActions m_DropperActionsCallbackInterface;
    private readonly InputAction m_Dropper_DropButton;
    public struct DropperActions
    {
        private @PlayerControls m_Wrapper;
        public DropperActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @DropButton => m_Wrapper.m_Dropper_DropButton;
        public InputActionMap Get() { return m_Wrapper.m_Dropper; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DropperActions set) { return set.Get(); }
        public void SetCallbacks(IDropperActions instance)
        {
            if (m_Wrapper.m_DropperActionsCallbackInterface != null)
            {
                @DropButton.started -= m_Wrapper.m_DropperActionsCallbackInterface.OnDropButton;
                @DropButton.performed -= m_Wrapper.m_DropperActionsCallbackInterface.OnDropButton;
                @DropButton.canceled -= m_Wrapper.m_DropperActionsCallbackInterface.OnDropButton;
            }
            m_Wrapper.m_DropperActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DropButton.started += instance.OnDropButton;
                @DropButton.performed += instance.OnDropButton;
                @DropButton.canceled += instance.OnDropButton;
            }
        }
    }
    public DropperActions @Dropper => new DropperActions(this);
    public interface IDropperActions
    {
        void OnDropButton(InputAction.CallbackContext context);
    }
}
